# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180703_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='detail',
        ),
        migrations.AddField(
            model_name='details',
            name='addres',
            field=models.TextField(default=200),
        ),
    ]
