# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180704_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='city',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='addres',
            field=models.TextField(default=0),
        ),
    ]
