# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180704_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='addres',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='details',
            name='city',
        ),
        migrations.RemoveField(
            model_name='details',
            name='pincode',
        ),
        migrations.AddField(
            model_name='details',
            name='e',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.employee'),
        ),
    ]
